### PR TITLE
1.17

### PR DESCRIPTION
**Pull request by shartte**
**NOTE:** I can't set a target-branch that doesn't exist in your repository, so the target is 1.16, even though that is obviously wrong :)

Launches into game, but rendering is still broken. I am still investigating that.

image

### CODE REVIEW

**Comment by shartte** [comment]
Better... Clearing the pose stack = not a good idea.

image

Still slightly odd lighting behavior for entities in the overlay, but it generally works.

image

**Comment by McJty** [comment]
Just back from vacation. I'll check this out tomorrow. Thanks

**Comment by McJty** [comment]
I made the 1.17 branch. Can you reapply this PR to that branch? Thanks

**Comment by shartte** [comment]
Done

**Comment by shartte** [comment]
I also worked a bit on JEI in the meantime and learned more about the new rendering, so I might come back and make more rendering fixes.
Shaders are complicated 😁

**Pull request merged**
