### PR TITLE
port to 1.18 fabric

### PR DESCRIPTION
**Pull request by AlphaMode**

### CODE REVIEW

**Comment by AlphaMode** [comment]
I don't know what todo the about the merge conflicts I based the branch off the existing 1.18 repo and not the old fabric one

**Comment by McJty** [comment]
Not exactly sure what to do with this to be honest. I don't have a fabric dev env and have no time to investigate in that so I can't really make a release out of this or do anything with this

**Comment by AlphaMode** [comment]
> Not exactly sure what to do with this to be honest. I don't have a fabric dev env and have no time to investigate in that so I can't really make a release out of this or do anything with this

Would it be ok if I just released to as another project in cf I could add you as a author

**Comment by McJty** [comment]
Yes, that's fine

**Comment by AlphaMode** [comment]
I'll close this then and just keep things on my repo

**Pull request closed without merging**
