### PR TITLE
Text Improvements.

### PR DESCRIPTION
**Pull request by Speiger**
-Added: ITextStyle has actually now a use.
-Added: Text Element can have a custom width/height now (forcing it)
-Added: TextElement can now have Padding so it can be moved.
-Added: TextElement can have alignment now. (Good For Titles of categories)
-Added: Legacy Support for CompoundText so it won't break

Since the ProgressBar patch was offically approved here is the next one.
ElementText can now actually use Styles that could be defined by the creator and don't rely on the fact of Compound Text readds the feature.
Legacy support was added for compound text but textstyles should be supported (vanilla)
Stringyfy method of OneProbe deletes all TextStyles unless they are hardcoded into the string itself.

### CODE REVIEW

**Comment by Speiger** [comment]
@McJty this patch is now compatible with your changes.
Also there is still a lot of patches coming. (This could at the current paste take a week or two)

**Comment by McJty** [comment]
I prefer it slow. There is no hurry

**Comment by Speiger** [comment]
Really depends on how you look at it. The 1-2 week ETA is not really a problem to me though we could be done in a day or two if we took only a couple hours (2-3) of validating everything. I mean i am literately copy pasting this from another project and editing it is not really hard. But that said take the time you need as long it gets in within a reasonable time (like insane would be a month for such little code) I have no problem with that.

**Comment by McJty** [comment]
I'm going to merge this but please use my code style in the future (i.e. starting curly brace on the same line as the 'if', 'switch', whatever)

**Comment by Speiger** [comment]
Yeah i will try to emulate it as good as possible. Issue is more about i need to apply this afterwards because it is written in my style.
Next patch coming in bit

**Pull request merged**
